---
area/admin:
  - client/src/components/admin/**/*
  - doc/source/admin
area/client:
  - client/**/*
area/datatypes:
  - lib/galaxy/datatypes/**/*
  - lib/galaxy/config/sample/datatypes_conf.xml.sample
area/documentation:
  - doc/**/*
area/jobs:
  - lib/galaxy/jobs/**/*
area/libraries:
  - client/src/components/LibraryFolder/**/*
  - lib/galaxy/webapps/galaxy/api/libraries.py
area/testing:
  - test/**/*
  - test-data/**/*
  - lib/galaxy/tools/test.py
  - run_tests.sh
area/testing/selenium:
  - lib/galaxy/selenium/**/*
  - lib/galaxy_test/selenium/**/*
area/tools:
  - tools/**/*
  - lib/galaxy/webapps/galaxy/api/tools.py
  - lib/galaxy/tools/**/*
  - tool-data/**/*
  - lib/galaxy/tool_util/**/*
area/toolshed:
  - client/src/toolshed/**/*
  - lib/galaxy/webapps/galaxy/api/toolshed.py
area/visualizations:
  - config/plugins/visualizations/**/*
