language: python
python: 2.7
matrix:
  include:
    - os: osx
      # No version of Python is available via virtualenv on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      env: TOX_ENV=py27-first_startup
install:
  - set -e
  - pip install tox
  - |
    if [ "$TOX_ENV" == "py27-first_startup" ]; then
        sh scripts/common_startup.sh
        wget -q https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
        mv db_gx_rev_0127.sqlite database/universe.sqlite
        sh manage_db.sh -c ./config/galaxy.yml.sample upgrade
    fi
script: tox -e $TOX_ENV
notifications:
  email: false
