name: Build Container Image
on:
  push:
    branches:
      - 'release*'
      - dev
concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'galaxyproject'
    steps:
      - uses: actions/checkout@v2
      # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set branch name
        id: branch
        run: echo "::set-output name=name::$(BRANCH_NAME=${GITHUB_REF##*/}; echo ${BRANCH_NAME/release_/})"
      - run: docker build . --build-arg GIT_COMMIT=$(git rev-parse HEAD) --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg IMAGE_TAG=${{ steps.branch.outputs.name }} --build-arg IMAGE_TAG=${{ steps.branch.outputs.name }} -t galaxy/galaxy-min:${{ steps.branch.outputs.name }} -f .k8s_ci.Dockerfile
      - run: docker tag galaxy/galaxy-min:${{ steps.branch.outputs.name }} quay.io/galaxy-min/galaxy:${{ steps.branch.outputs.name }}
      - name: Login to quay.io
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY_URL: quay.io
      - name: Push to quay.io with branch name
        uses: actions-hub/docker@master
        with:
          args: push quay.io/galaxy-min/galaxy:${{ steps.branch.outputs.name }}
