name: Update dependencies
on:
  schedule:
    - cron: '0 3 * * 6'  # Run every saturday at 3 am.
jobs:
  update_dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
      - name: Update dependencies
        run: | 
          python -m venv .venv
          make update-dependencies
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Python dependencies
          title: Update Python dependencies
          body: Run `make update-dependencies`.
          branch: dev_auto_update_dependencies
          delete-branch: true
          labels: area/dependencies
